config/routes.rb
FinalProject::Application.routes.draw do

  root :to => 'home#index'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  get '/questions/finish/:assignment_id' => 'questions#finish'
  post '/start_quiz' => 'classrooms#assign'
  get '/sms' => 'sms#create'
  resources :users, :homeworks, :classrooms, :assignments, :questions, :tags, :responses, :answers

end

app/models/classroom.rb
# == Schema Information
#
# Table name: classrooms
#
#  id         :integer          not null, primary key
#  subject    :string(255)
#  teach_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  random     :string(255)
#

class Classroom < ActiveRecord::Base
attr_accessible :subject, :teacher_id
before_save :generate_random
has_many :homeworks
has_and_belongs_to_many :users

  def students
    users.reject {|u| u.is_teacher }
  end

  def teacher
    User.find(self.teach_id)
  end

  def generate_random
    self.random = SecureRandom.hex(2)
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classrooms = Classroom.all
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.create(params[:classroom])
  end

  def show
    @classroom = Classroom.find(params[:id])
    @students = @classroom.students
  end


  def assign
    @classroom = Classroom.find(params[:classroom_id])
    @assignment = Assignment.find(params[:assignment_id])
    @questions = @assignment.questions
    @classroom.students.each do |student|
      homework = Homework.create(user_id: student.id, classroom_id: @classroom.id)
      homework.questions = @assignment.questions
      homework.save
      body = "You have a new homework from your #{@classroom.subject} class. Text projects to access this homework."
      Text.send_text_to(student.phone, body)
    end
  end
end

app/views/classrooms/_form.html.haml
.row
  .large-8.columns
    %h3
      Create a New Classroom
    #classroom_form
      = form_for @classroom, :remote => true do |f|
        = f.text_field :subject, :autofocus => true, :placeholder => 'Subject'
        = f.text_field :teacher_id, :placeholder => 'Teacher ID'
        = f.submit 'Create Classroom', :class => 'button tiny radius success'

app/views/classrooms/_student.html.haml
.row
  .large-12.columns
    %h2
      Classroom Roster
      -if @classroom.users.present?
        - @users.each do |user|
          = user.name

    

app/views/classrooms/assign.js.erb
$('#body').empty().append('<%=j render :partial => '/assignments/assignments' %>')

app/views/classrooms/create.js.erb
$('#classroom_form').empty().append('<h5> You created a new classroom. </h5>').slideDown('slow');

app/views/classrooms/index.html.haml
.row
  %h2
    Classrooms

  .large-4.columns
    = link_to 'Create New Quiz', new_assignment_path, remote: true, class: 'button tiny radius'
    = link_to 'Load quiz', assignments_path, remote: true, class: 'button tiny radius'


  .large-4.columns
  = link_to('New Classroom', new_classroom_path, remote: true,  class: 'button tiny success') if @auth.present?
  #form
  #body

  #show_classroom
    - @classrooms.each do |classroom|
      = classroom.subject

%svg

app/views/classrooms/new.js.erb
$('#form').empty().hide().append('<%=j render(:partial =>'form') %>').slideDown('slow').show("fold", 500);

app/views/classrooms/show.html.haml
.row
  = "Classroom Id: #{@classroom.random}" if @classroom.random.present?
.row#classroom_id{:'data-classroom-id' => @classroom.id}
  .large-4.columns
    = link_to 'Create New Quiz', new_assignment_path, remote: true, class: 'button tiny radius'
    = link_to 'Load quiz', assignments_path, remote: true, class: 'button tiny radius'

    #form
    #body
    = render partial: "/users/student", collection: @students, :as => :student
%svg